### ISSUE TITLE
error at shutdown

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/spalloc#23]
Getting spikes for pop_1
|0%                          50%                         100%|
 ============================================================
2018-04-22 09:09:21 INFO: Turning off machine
Exception in thread SpallocJobController:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/media/alan/DATA/spinnaker_software/SpiNNFrontEndCommon/spinn_front_end_common/abstract_models/impl/machine_allocation_controller.py", line 49, in __manage_allocation
    self._teardown()
  File "/media/alan/DATA/spinnaker_software/SpiNNFrontEndCommon/spinn_front_end_common/interface/interface_functions/spalloc_allocator.py", line 60, in _teardown
    self._job.close()
  File "/media/alan/DATA/spinnaker_software/spalloc/spalloc/job.py", line 391, in close
    self._keepalive_process.communicate(input="exit\n".encode("ascii"))
  File "/usr/lib/python2.7/subprocess.py", line 786, in communicate
    self.stdin.write(input)
ValueError: I/O operation on closed file

Process finished with exit code 0

happesn with standard synfire chain, at any run.

**Comment by rowleya** [comment]
I believe this was fixed in SpiNNakerManchester/SpiNNFrontEndCommon#311 - try pulling master of FEC and see if this fixes the issue

**Comment by alan-stokes** [comment]
can verify that pulled master into parallel java multi board has indeed eradicated this error. thus closing
